# Generated by Django 4.0.3 on 2022-03-18 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.UUIDField(default=uuid.UUID('1628aa73-5d6f-4cf4-ba00-7493d9d41dbe'), editable=False)),
                ('group_name', models.CharField(max_length=500, unique=True)),
                ('number_of_users', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.UUID('d55f38a7-2dcb-463e-bf34-c436ae582d9d'), editable=False)),
                ('content', models.TextField(default='')),
                ('date_time_sent', models.DateTimeField(auto_now=True, verbose_name='Time sent')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minified_chat.group')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
